### ISSUE TITLE
Update ACS regression tests to use new CTE algo and truth

### ISSUE THREAD

**Issue by pllim** [spacetelescope/hstcal#121]
I expect existing ACS/WFC tests involving PCTECORR to fail horribly until the following is done in the dev test suites:

* Update PCTETAB to use new reference file.
* Update truth images with new expected results -- Being a purist, I would manually generate the first batch and copy them into "ref". But you can choose to use the OK button too but you need to inpect the diff carefully first.

**Comment by jamienoss** [comment]
Done.
