### ISSUE TITLE
WFC3 CTE: incorporate new CTE implementation used in ACS CTE

### ISSUE THREAD

**Issue by jamienoss** [spacetelescope/hstcal#125]
In issue #101 the CTE implementation present in calwf3 was re-written and implemented as the upgrade to the second generation cte algorithm for calacs.

This should now be incorporated into calwf3.

This addresses the following issues:

#20 
#46 
#48 (resolved by #110)
#54 
#61 (Critical Bug)
#72 

The current effort for this is https://github.com/jamienoss/hstcal/commits/cte-dev and is fairly complete.

**Comment by mdlpstsci** [comment]
The WFC3 CTE correction is now more advanced (PR#461) and efficient as compared to the implementation done in ACS.  As such, this issue is being closed.
