### ISSUE TITLE
Optimize ACS CTE Gen 2 even more (if possible)

### ISSUE THREAD

**Issue by pllim** [spacetelescope/hstcal#165]
See discussions starting around https://github.com/spacetelescope/hstcal/issues/160#issuecomment-312058394 .

**Comment by jamienoss** [comment]
I would suggest removing the 'ACS' from the title and adding the WFC3 label - any improvement will be in the joint code base [hstcal/ctegen2](https://github.com/spacetelescope/hstcal/tree/master/ctegen2).

In addition, just an FYI, this is already on my future to do list. This would primarily be working to improve the auto-vectorization.
