### ISSUE TITLE
wf3rej.e lacks proper argument parsing and checking

### ISSUE THREAD

**Issue by jamienoss** [spacetelescope/hstcal#195]
The following code should check whether the cmd line options passed to it are allowed.

[int rej_command (int argc, char **argv, char **input, char *output,
                clpar *par, int newpar[])](https://github.com/spacetelescope/hstcal/blob/master/pkg/wfc3/calwf3/wf3rej/rej_command.c#L29-L166)

```c
...
/* Not enough arguments or just wants version number; List all options for user */
    if (argc < 3  ) {
        if (argc >= 2){
            if (strcmp("-r", argv[1]) == 0) { 
                printf ("Current version: %s\n", WF3_CAL_VER);
                exit(0);
            }
            if (argv[ctoken][2] == '-') {
                printf("You need to speficy an output image name");
                exit(0);
            }
        } else {
            printf(" wf3rej input output [-t] [-v]");
            printf("                    [-shadcorr] [-crmask]\n ");
            printf("                    [-table <filename>] [-scale #]\n");
            printf("                    [-init (med|min)] [-sky (none|mode)]\n");
            printf("                    [-sigmas #] [-radius #] [-thresh #]\n");
            printf("                    [-pdq #]\n"); 
            printf("                    [-r]\n");
            exit(ERROR_RETURN);
        }
    }
...
```

Should have some checking similar to other exectuables:

```c
...
for (i = 1;  i < argc;  i++) {
   ...
   if (argv[i][0] == '-') {
        for (j = 1;  argv[i][j] != '\0';  j++) {
             ....
   } else {
					printf ("Unrecognized option %s\n", argv[i]);
					exit (ERROR_RETURN);
				}
			}
		} else if (input[0] == '\0') {
			strcpy (input, argv[i]);
		} else {
			too_many = YES;
		}
	}

	if (input[0] == '\0' || too_many) {
		printf ("syntax:  calwf3.e [-t] [-s] [-v] [-q] [-r] [-1] input \n");
		exit (ERROR_RETURN);
	}

...
```

Tidy up a few other oddities also, e.g.

```c
...
   if (argc < 3  ) {
        if (argc >= 2){
...
```

For ``argc < 3`` bounding, ``argc >=2`` should just be:
```c
...
 if (argc < 3  ) {
        if (argc == 2){
...
```

 ### Segfault

In fact, the checking is incorrect enough to cause it to segfault, i.e.  ``wf3rej.e --dummy'', [here](https://github.com/spacetelescope/hstcal/blob/master/pkg/wfc3/calwf3/wf3rej/rej_command.c#L78).

```c
strcpy (output, argv[2]);
```

This is due to the combination of ``ctoken`` being initialized to 0 rather than 1 as ``argv[0]`` is the executable name itself. I n addition the check for a second '-' is checked against the 3rd character and not the second. [Source here](https://github.com/spacetelescope/hstcal/blob/master/pkg/wfc3/calwf3/wf3rej/rej_command.c#L56-L58):

```c
...
    if (argv[ctoken][2] == '-') {
        printf("You need to speficy an output image name");
        exit(0);
    }
...
```

``if (argv[ctoken][2] == '-')`` should be ``if (argv[ctoken][1] == '-')``, with `` int ctoken = 1`` . This causes ``argv[2]`` to be accessed and copied by ``strcpy()`` when it doesn't exist. ``argc = 2``, therefore ``argv`` is bound by the last index, 2. @jhunkeler this is the segfault you noted in this [comment](https://github.com/spacetelescope/hstcal/pull/194#issuecomment-320455236) in #194 .

**Comment by mdlpstsci** [comment]
This was resolved by PR#574.
