### ISSUE TITLE
Revamp the PHOTCORR step for ACS to be like CALWF3 for UVIS

### ISSUE THREAD

**Issue by mdlpstsci** [spacetelescope/hstcal#220]
This is migrated issue 1221 from the Trac system.  It needs to be determined if this is still a desired enhancement.  Here is the Trac commentary.

Trac
There is now some discussions within the ACS Team to revamp the PHOTCORR step for WFC to be like CALWF3 for UVIS (see #1011).   The information in #1011 is lengthy, but here is the URL:
https://trac.stsci.edu/ssb/stsci_python/ticket/1011.

**Comment by pllim** [comment]
This is a duplicate for #45. It is a no-go.

**Comment by mdlpstsci** [comment]
HI,

You are supposed to be enjoying your workshop!  I figured it and possibly the other old Trac issue might be zombies, but I am reminding Norman.  I am really after his prioritizing the open ACS issues.  Hope you are learning lots of good Pythonese kind of stuff.

M

**Comment by mdlpstsci** [comment]
As discussed above, this work will not be done.
