### ISSUE TITLE
Make -j <n> doesn't work

### ISSUE THREAD

**Issue by jamienoss** [spacetelescope/hstcal#232]
HSTCAL is actually built using ``waf`` rather than ``make``. As a workaround the configure process creates a Makefile such that it can be built using ``make``. This simply just calls ``waf`` though and ``waf`` and ``make`` have opposite defaults to parallel building. ``waf`` builds in parallel by default (I think, need to double check this) whilst ``make``'s default is single build execution.

What needs to happen is for the ``n`` in ``make -j <n>`` to be passed to the waf build. The problem is that ``make`` has no way of doing this. There is no way to retrieve ``n``. The best that you can do is search the ``$(MAKEFLAGS)`` var to see if ``-j`` or ``--jobs`` were used at all. When using either of these ``echo $(MAKEFLAGS)`` yields ``--jobserver-fds=3,4 -j`` irrespective of ``n`` and whether ``-j`` or ``--jobs`` was used. Searching for just 'j' is adequate.

 The solution could at least be to warn and/or to force ``waf`` to not parallel build when ``make`` is invoked without any parallel options.

I came across this when requiring a deterministic build log to compare generated warnings. I noticed that ``\make`` or ``make -j 1`` gave non-deterministic results due to parallelism. This is an issue that I should have opened months ago, better now than never.

**Comment by mdlpstsci** [comment]
This issue is soon to be obsolete based upon merging of PR #412.  I am closing this issue as PR #412 is planned to be part of the next HSTDP build (2023.4.0?).
