### ISSUE TITLE
Localize global objects MsgText and instances of TrlBuf

### ISSUE THREAD

**Issue by jamienoss** [spacetelescope/hstcal#234]
In relation to #191 & #207 

Currently, ``MsgText`` is instantiated globally within the scope of each ``main()``. It is then referenced within library code in ``lib/trlbuf.c``, _c.f._ #191. This breaks this library as it prevents intra-library use of the referencing functions. ``MsgText`` must be removed as a global and incorporated into the library interface.

The same is true for instances of the struct ``TrlBuf``.

This is a considerable refactor, deferred from both #191 & #207 to this issue and future work.

**Comment by mdlpstsci** [comment]
While this is a good idea, it is not necessarily worth applying scarce resources to a task which offers no user-based improvement.
