### ISSUE TITLE
'status' may be used uninitialized in ACS gen1 CTE

### ISSUE THREAD

**Issue by jamienoss** [spacetelescope/hstcal#237]
Noncritical bug due to the function being replaced by gen2 CTE.

The following [reference](https://github.com/spacetelescope/hstcal/blob/master/pkg/acs/calacs/acscte/pcte_fixycte.c#L272) to ``status`` may be used uninitialized. This is due to it being accounted for as ``private`` in the openMP [pragma](https://github.com/spacetelescope/hstcal/blob/master/pkg/acs/calacs/acscte/pcte_fixycte.c#L173) but these are not initialized when instantiated per thread.

```c
pragma omp parallel for schedule(dynamic) \
      private(i,j,n,status,cte_frac_col,new_cte_frac,ncf_top,ncf_bot,\
              high_found,high_location,redo_col,num_redo,pix_obs,pix_cur,pix_read) \
      shared(sig_cte,sig_cor,cte_frac)
```

Possible solutions:
 * initialize to ``HSTCAL_OK`` per iteration (have to check logic)
 * split ``omp parallel for`` into separate ``omp parallel``, init local ``status``, then ``omp for``. Correct implementation of existing code.

```c
...
#   pragma omp parallel private(i,status,j,n,cte_frac_col,new_cte_frac,ncf_top,ncf_bot,\
        high_found,high_location,redo_col,num_redo,pix_obs,pix_cur,pix_read) \
        shared(sig_cte,sig_cor,cte_frac)
      status = HSTCAL_OK;
#pragma omp for schedule(dynamic)

    /* loop over columns. columns are independent of each other. */
    for (j = 0; j < arry; j++) {
...
```

### Important
In addition, its mismatched use of global vs private local is incorrect. ``status`` is finally returned but it will never be populated by any of the threads.

_c.f._ #187

**Comment by pllim** [comment]
Gen 1 is retired.
