### ISSUE TITLE
Fix realloc bugs in trlbuf.c

### ISSUE THREAD

**Issue by jamienoss** [spacetelescope/hstcal#243]
The following [bug exists](https://github.com/spacetelescope/hstcal/blob/master/pkg/acs/calacs/lib/trlbuf.c#L355-L357) in ``pkg/acs/calacs/lib/trlbuf.c``.

```c
...
 oprefix = realloc (oprefix, (strlen(oprefix) + strlen(buf) +2 ));
 if (oprefix == NULL)
     //error
...
```

The correct pattern for using ``realloc()`` is to use a tmp pointer.
```c

...
char * oprefix = NULL;
...
void * ptr = realloc (oprefix, (strlen(oprefix) + strlen(buf) +2 ));
if (!ptr)
{
    //error message
    if (oprefix)
    {
         free(oprefix); // Only free if having ownership, which this func does.
         oprefix = NULL;
    }
    return; // or whatever
}
oprefix = ptr;
ptr = NULL;
...
```

The reason for this is that when ``realloc(ptr, length)`` fails it leaves ``ptr`` as is and only returns ``NULL``. In the original case, ``oprefix`` would be set to this ``NULL`` value, overwriting the original address thus leaking it.

@stsci-hack the following [comment](https://github.com/spacetelescope/hstcal/blob/master/pkg/acs/calacs/lib/trlbuf.c#L322-L323) is present for this particular function.
```
18 Jan 2002 (WJH): Removed extraneous, bug-ridden 'tmpptr' buffer used
        during reallocation of oprefix buffer size.
```
and @hbushouse in [calwf3/lib/trlbuf.c](https://github.com/spacetelescope/hstcal/blob/master/pkg/wfc3/calwf3/lib/trlbuf.c#L267-L268)
```
21 June 2002 (HAB): Removed extraneous, bug-ridden 'tmpptr' buffer used
	during reallocation of oprefix buffer size (following CALACS changes).
```
Are you able to explain more?

This issue is true for many of the calls to ``realloc()`` in this file and its ``WFC3`` counterpart. 

There are also issues where ``realloc()`` seems to be oddly used instead of ``malloc()``. E.g. [here](https://github.com/spacetelescope/hstcal/blob/master/pkg/acs/calacs/lib/trlbuf.c#L432)
```c
...
if ( (trlbuf.buffer = realloc (NULL, INIT_LEN)) == NULL){
...
```
It is also an issue that length is used instead of explicitly size. This is only correct if ``trlbuf.buffer`` is of type ``char``. Which it is, however, it does make this code brittle to type changes to the underlying struct members. This is true for all calls to ``realloc()``.

These are commoned by #191 and fixed by its associated PR #235 

### Update

Warren pointed me to the original PR that removed the original use of a ``tmpptr`` from ``realloc()``.
[trac issue](https://trac.stsci.edu/ssb/stsci_python/changeset/4902/stsdas/trunk/stsdas/pkg/hst_calib/acs/calacs). The original code looked like this:
```c
tmpptr = realloc (oprefix, (strlen(oprefix) + strlen(buf) +2 )); 
if (tmpptr == NULL) {
    asnmessage ("Out of memory: Couldn't store trailer file comment.");
    status = OUT_OF_MEMORY; 
    /* Clean-up... */ 
     free (trlbuf.buffer); 
    free (trlbuf.preface);
    free (oprefix); 
    fclose (trlbuf.fp); 
    return (status); 
}
else
{ 
    free(oprefix);
    oprefix = tmpptr;
    tmpptr = NULL;
...
}
...
```
The bug wasn't the use of a temp ptr, this is the correct thing to do, the bug was the ``free(oprefix);`` upon the success of the reallocation. I.e. the ``else`` branch should have looked like this:
```c
...
else
{ 
    oprefix = tmpptr;
    tmpptr = NULL;
...
}
```
The correct fix was just deleting this one line. The reason for this is that ``realloc`` will expand the address space used if it can and in this case can return you the exact same pointer that existed before the call to ``realloc``.

**Comment by jamienoss** [comment]
@mdlpstsci FYI

**Comment by stsci-hack** [comment]
You can find the actual code change from 2002 here:
https://trac.stsci.edu/ssb/stsci_python/changeset/4902/stsdas/trunk/stsdas/pkg/hst_calib/acs/calacs

This may help guide your current work.
