### ISSUE TITLE
Add tastis functionality to STIS

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/hstcal#266]
tastis: analyze STIS target acquisition images.

I have a note here about "needs investigation, IRAF named interface to files".  I don't remember exactly what this means, will update with meaning when I get to it.

Also a note I'm not sure about:      tastis.h - This header file needs to be added in (header file doesn’t import anything itself, just sets up variables and struct)

**Comment by stscicrawford** [comment]
Closing as this will be implement in the STISTools package.
