### ISSUE TITLE
Remove WFC3 & ACS includes from ctegen2 library code 

### ISSUE THREAD

**Issue by jamienoss** [spacetelescope/hstcal#267]
There exist includes and references to the other instruments, e.g. wfc3, from the ctegen2 library code.

[ctegen2/ctehelpers.c](https://github.com/spacetelescope/hstcal/blob/master/ctegen2/ctehelpers.c#L7)
```c
#include "wf3.h" //need to remove this dependency
```
[ctegen2/wscript](https://github.com/spacetelescope/hstcal/blob/master/ctegen2/wscript#L11-L14)
```python
 includes = ['.',
                    '../pkg/acs/calacs/acscte/',
                    '../pkg/acs/calacs/include/',
                    '../pkg/wfc3/calwf3/include/',
                    '../pkg/wfc3/calwf3/wf3cte/',
```

**Comment by pllim** [comment]
https://github.com/spacetelescope/hstcal/pull/412 is merged. We no longer use waf
