### ISSUE TITLE
HSTDP-2017.1 is for bugfix only?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/hstcal#27]
[HSTDP-2017.1](https://github.com/spacetelescope/hstcal/milestone/2) is for bugfix only?

**Comment by stsci-hack** [comment]
HSTDP 2017.1 is only planned for RHEL7 upgrade for the pipeline.   It is not clear whether any changes to instrument calibration code could be supported at all, with the most likely option being to leave critical bug fixes as separate quick fixes.
