### ISSUE TITLE
Update regression test truth files to reflect #271

### ISSUE THREAD

**Issue by jamienoss** [spacetelescope/hstcal#272]
#271

**Comment by pllim** [comment]
This issue has been open for a while. Is it still relevant?

**Comment by mdlpstsci** [comment]
All the HSTCAL ACS truth files have been updated as the pipeline has been modified.  There one test marked as skip to process 4 datasets (CTE makes the tests slow).  I ran one of the datasets to make sure the test passes, and it did.  I also looked at Artifactory and can see the truth files have been updated as necessary.
