### ISSUE TITLE
refactor LoadHdr, move into hstio

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/hstcal#284]
Under recommendation/ cherry pick @jamienoss's fix, moving LoadHdr from loadhead.c in the acs and wfc3 folders into the hstio.c file.  Need to access this function for my STIS function imports (#262).

**Comment by jamienoss** [comment]
@SaraOgaz  Hey, so that this isn't holding you up, just copy [LoadHdr()](https://github.com/spacetelescope/hstcal/blob/master/pkg/acs/calacs/lib/loadhead.c#L19-L54) directly to `tastis.c`. You may need to add some needed includes. Make it static for now also.
