### ISSUE TITLE
Discuss runtime library stability

### ISSUE THREAD

**Issue by jamienoss** [spacetelescope/hstcal#321]
Opened to discuss what we want and/or should want for the runtime stability of hstcal across different OSs and hd architectures.

Basically:
* what do we want to do about ``libgcc``? 
* what/how do we want to constrain rt floating pointing computation fluctuations?

From what I have understood, our supported/mandated version is that which we use in prod (can never remember the acronym for this group, sorry guys), which is whatever gets shipped with RHEL 6/7, I think ``GCC`` 4.7.something. When we build the prod dist we do so on the same OS as the prod machines, we, therefore, use the (archaic) shipped dist of GCC. However, when we build the Linux conda release for the public, whilst we do so on the same build machine, we do not link statically (I'm not even sure if you can against ``libgcc`` or whether you should even try) and therefore rely on the dist. version of the linux flavour conda is installing it on. This is true because of the ``[osx]`` specifier on the ``gcc`` and ``libgcc`` build & rt requirements. This would be a good reason to remove them as is _now_ done in the [dev build recipe](https://github.com/astroconda/astroconda-dev/blob/master/hstcal/meta.yaml). This way you would at least have some conformity between Linux and OSX and across the diff version of each. However, we may also have to tether to a single version so as to (attempt) to conform with the prod build. I say "attempt" and "at least some conformity" because it is ultimately impossible for us to be responsible for ``libgcc`` across platforms, and the libs that it is dependent on, i.e. ``GMP``, ``MPFR``,   & ``MPC``. So we would tether to the version that we use for prod _OR_ we build the prod dist. with the conda dist. of ``GCC``. This would also allow us to move away from the >decade old version of GCC.

I raised this issue (offline) about a year+ ago when working on the CTE correction. This question has recently raised its head again with #320 and #306.

Loosely related is #88

**Comment by mdlpstsci** [comment]
Closing as there are many more issues of priority to address with limited resources.
