### ISSUE TITLE
TST: Move the rest of active pandokia tests to Jenkins + Artifactory

### ISSUE THREAD

**Issue by pllim** [spacetelescope/hstcal#340]
Move the following tests over:

- [x] ACS
- [x] WFC3

Note: STIS tests are already handled by spacetelescope/stistools#48 by @SaOgaz .

**Comment by pllim** [comment]
@mdlpstsci , did your #349 completely address this? I see that you have already opened up separate follow-up issues. In another word, can we stop running pandokia tests yet for HSTCAL?

**Comment by mdlpstsci** [comment]
Yes, we can stop running Pandokia tests for ACS and WFC3 with the understanding:
(1) Please do not remove any of the input or truth files on the test machines, and
(2) Some of the tests are not yet running with Jenkins/Artifactory as they are marked as xfail.

**Comment by pllim** [comment]
@stscicrawford , do you have a preference whether pandokia should be out of the picture now or later?

**Comment by stscicrawford** [comment]
Tests have been migrated, and issues have been opened for the few that need to be further investigated..  I'm happy to have this closed and pandokia turned off.

**Comment by pllim** [comment]
@rendinam has turned them off but we won't know till tomorrow's run. :smile: :crossed_fingers:

**Comment by pllim** [comment]
Confirmed that HSTCAL no longer runs on pandokia. 🎉
