### ISSUE TITLE
TST: Auto-upload failed test results?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/hstcal#342]
For an example on how it works, consult spacetelescope/drizzlepac#156 and Innerspace document.

Pros: When a test fails but you are unable to produce an exact truth locally, it is possible to "copy over" the new truth from the desired run to the "truth" location.

Cons: If a lot of tests fail in a run over many runs, they might eat up available storage, possibly preventing others from using the affected storage.

Depends on spacetelescope/ci_watson#10

**Comment by mdlpstsci** [comment]
This was implemented by someone (Joe?) as the "new" truth files are uploaded to Artifactory.  Indeed, there are some old results which are taking up a lot of space as the directories have to be deleted individually.  In any case, this issue was implemented -- closing.
