### ISSUE TITLE
TST: Mark some tests as slow

### ISSUE THREAD

**Issue by pllim** [spacetelescope/hstcal#354]
As per https://github.com/spacetelescope/hstcal/pull/349#issuecomment-421091228

**Comment by pllim** [comment]
I feel like marking more as slow to be handled internally via nightly run can also reduce the risk of timeout problems in push events. Example: https://ssbjenkins.stsci.edu/blue/organizations/jenkins/STScI%2Fhstcal/detail/master/6/pipeline

**Comment by mdlpstsci** [comment]
Timeouts do not seem to be much of a problem at this time.  However, minimizing the number of slow tests which need to be executed is overall a good idea.
