### ISSUE TITLE
Will there be a Dockerfile here?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/hstcal#400]
This was asked by @arfon at the 2019-02-07 Jupyter Science Initiative meeting. I don't think it was answered, so I am posting it here for further discussions.

Question: When start to deploy HSTCAL on JupyterHub using Docker images, will we also distribute that Dockerfile here?

p.s. If I misunderstood the question, please correct me.

**Comment by mdlpstsci** [comment]
When an HSTDP build is generated, the HSTCAL package is distributed for DMS as a YML file at [URL](https://github.com/astroconda/astroconda-releases/tree/master/caldp), as well as a docker image (Linux snapshot only) to https://hub.docker.com/repository/docker/stsci/hst-pipeline.
