### ISSUE TITLE
New PHOTCORR for CALACS

### ISSUE THREAD

**Issue by pllim** [spacetelescope/hstcal#45]
See https://trac.stsci.edu/ssb/stsci_python/ticket/1221 (new PHOTCORR). This was broken off from #13, which has a definite delivery timeline now.

Note: The last I heard, this might not happen because zeropoints are similar between WFC1 and WFC2. But keeping this open for now.

**Comment by pllim** [comment]
No mention of this from ACS Team for a while now, so closing.

**Comment by jamienoss** [comment]
@pllim did you work on this at all? If yes can you link your branch please?

**Comment by pllim** [comment]
No. Work never started and not likely ever will.
