### ISSUE TITLE
Installation test "./waf test" breaks in python3

### ISSUE THREAD

**Issue by sean-lockwood** [spacetelescope/hstcal#524]
There were two python 2 print statements that broke "./waf test" here:
https://github.com/spacetelescope/hstcal/blob/master/hstio/test/test_hstio.py#L20

Also fix `pyfits` import.

_Originally posted by @sean-lockwood in https://github.com/spacetelescope/hstcal/pull/523#issuecomment-690328854_

**Comment by pllim** [comment]
Apparently the author was `astropy-buildbot`. I have no idea what it is. It is definitely not used by `astropy`.

Also, we never run `./waf test`. 🤷
