### ISSUE TITLE
Use acstools acscte on different data

### ISSUE THREAD

**Issue by vpicouet** [spacetelescope/hstcal#565]
Hello,
I am working on another project (FIREBall https://arxiv.org/abs/2101.01920), on which we also experience poor CTE on an eletron multiplying CCD.
Is there a way to use acstools acscte method on our data?
For now I am getiing the error:
```
Read in Primary header from /image000964.fits...
Skipping 
image000964.fits because PCTECORR is not set to PERFORM
ERROR:    Can't open file 
```

 and if I add this myself I will continuously get errors  with 'PCTECORR, ROOTNAME, DETECTOR, EXPSTART, EXPEND...

Is there a way i couldmake the code work on my data?
Thanks for your help/time
Best

**Comment by mdlpstsci** [comment]
Good Morning,
I can understand that you might want to use the algorithm which has been implemented for the ACS CTE correction, but I doubt very much the _**actual code**_ will work for your data.  The implementation is customized to the HST ACS in terms of its data characteristics (e.g. structure, size, shape of input, semantic meaning), as well as the specifics of the ACS instrument.

To find out more about the CTE algorithm, it could be helpful for you to look at some of the Instrument Science Reports for ACS which discuss CTE.  You can look at the ACS reports

https://www.stsci.edu/hst/instrumentation/acs/documentation/instrument-science-reports-isrs

or the WFC3 reports

https://www.stsci.edu/hst/instrumentation/wfc3/documentation/instrument-science-reports-isrs

Best and Good Luck!
