### ISSUE TITLE
Fix failing WFC3 tests

### ISSUE THREAD

**Issue by pllim** [spacetelescope/hstcal#58]
On `pembry` dev:

https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=38236811
https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=38236815

**Comment by sosey** [comment]
yah, every time I've tried to log in to go over this one pembry has been down, I'll try and get to it this week.

**Comment by pllim** [comment]
Saw this popped up today for WFC3 on pembry public -- https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=30945

**Comment by sosey** [comment]
it looks like it dropped the connection to crds during test.
