### ISSUE TITLE
python 2 compatibility?

### ISSUE THREAD

**Issue by pcschneider** [spacetelescope/hstcal#594]
Dear HSTCAL-Team, 

wscript uses the 'exist_ok'-option of os.makedirs (see link below), but this was introduced only in python version 3.2, and the source installation fails if '`#!/usr/bin/env python`' executes python with version < 3.2; at least for me and probably generally. 

I think that '#!/usr/bin/env python3' together with requiring python >=3.2 would eliminate the issue.

Cheers,
Christian

https://github.com/spacetelescope/hstcal/blame/fc603b22a4fc3cc20570def74ee82ffc08fd5f62/wscript#L255

**Comment by pllim** [comment]
We just merged https://github.com/spacetelescope/hstcal/pull/412 so we no longer uses Python to build C code. I do not think this is relevant anymore. Thanks for your patience!
