### ISSUE TITLE
wf3cte - subarray to full frame corner mapping issue

### ISSUE THREAD

**Issue by jamienoss** [spacetelescope/hstcal#63]
[In this section of code](https://github.com/spacetelescope/hstcal/blob/master/pkg/wfc3/calwf3/wf3cte/wf3cte.c#L368-L369) which value should ``finish`` actually have, can we please double check?

```C
finish = start + subab.sci.data.nx + 2103;
finish = start + subab.sci.data.nx;
```

**Comment by jamienoss** [comment]
@sosey

**Comment by sosey** [comment]
yikes, how did that get through :/  
I believe the second one. We tested all the subarrays to make sure they were identified correctly, and pushing into the next quad makes no sense. Feel free to delete the prior line.
