### ISSUE TITLE
Switch to Python 3.6 in Travis?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/hstcal#73]
I notice `.travis.yml` still uses Python 3.5. Should we just use 3.6 now, or is that somehow coordinated with HSTDP?

**Comment by sosey** [comment]
@stsci-hack should verify, but delivery of updated python kernel needs to be coordinated with HSTDP. That doesn't mean we can't test 3.6, but we need to be at least testing what's being delivered to DP right now and anything cos/drizzlepac as well as the other python packages are supporting.

**Comment by pllim** [comment]
Would be nice to make sure `waf` still works in Python 3.6 when we are able to switch. Or if Joe and Jamie manage to replace it with `cmake`, then we can completely remove Python from the picture here. :wink:

**Comment by pllim** [comment]
Actually, I take a little back... If #71 is merged, we do still use Python but only for testing. In that case, I think it is okay to just use latest Python (e.g., 3.6) since it is not something HSTDP would care about.
